server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.34.251:8848
        username: nacos
        password: nacos
      config:
        server-addr: 47.99.34.251:8848
        username: nacos
        password: nacos
        file-extension: yaml
        import-check:
          enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
        - id: merchant-service
          uri: lb://merchant-service
          predicates:
            - Path=/merchant/**,/dish/**,/cart/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
